const INFOPAGE_ROUTE_PARAMS_CACHEKEY = 'info_params'
const SEARCH_RESULT_HISTORY_CACHEKEY = 'search_result_history'
const SEARCH_ENDPOINT = 'http://127.0.0.1:8000/api/v1/recipes/search/'

export { INFOPAGE_ROUTE_PARAMS_CACHEKEY, SEARCH_RESULT_HISTORY_CACHEKEY, SEARCH_ENDPOINT }